---
# https://github.com/nvm-sh/nvm
nvm_version: 0.39.0
# Franz https://meetfranz.com/
franz_version: 5.7.0

apt_repos:
  - ppa:solaar-unifying/stable
  - ppa:cappelikan/ppa

apt_pkgs:
  - bash
  - bash-completion
  - build-essential
  - curl
  - docker
  - pgadmin4
  - git
  - gimp
  - vim
  - flameshot                        # https://github.com/flameshot-org/flameshot
  - shellcheck                       # https://github.com/koalaman/shellcheck
  - htop
  - solaar                           # https://pwr-solaar.github.io/Solaar/
  - firefox
  - terraform
  - mainline                         # https://github.com/bkw777/mainline

snap_pkgs:
  - discord
  - fast
  - postman
  - slack
  - spotify
  - teams
  - telegram-desktop
  - cacher                           # https://www.cacher.io/

pip_pkgs:
  - ansible-lint
  - yamllint
  - s3cmd
  - docker
  - boto
  - boto3
  - botocore
  - terminator
  - molecule
  - molecule-docker
  - setuptools

nvm_url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh

deb_pkgs:

  - name: franz
    url: https://github.com/meetfranz/franz/releases/download/v{{ franz_version }}/franz_{{ franz_version }}_amd64.deb

  - name: vscode
    url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
