---
# https://github.com/nvm-sh/nvm
nvm_version: 0.39.5
# Franz https://meetfranz.com/
franz_version: 5.10.0

apt_key:
  - https://www.pgadmin.org/static/packages_pgadmin_org.pub
  - https://apt.releases.hashicorp.com/gpg
  - https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
  - https://apt.fury.io/wez/gpg.key

apt_repos:
  - ppa:solaar-unifying/stable
  - ppa:cappelikan/ppa
  - deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main
  - deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *

apt_pkgs:
  - apt-transport-https
  - bash
  - bash-completion
  - build-essential
  - curl
  - docker
  - pgadmin4
  - git
  - gimp
  - vim
  - shellcheck   # https://github.com/koalaman/shellcheck
  - htop
  - solaar       # https://pwr-solaar.github.io/Solaar/
  - firefox
  - terraform
  - mainline     # https://github.com/bkw777/mainline
  - unzip
  - w3m
  - tmux
  - nmap
  - iotop
  - thunderbird
  - silversearcher-ag  # https://github.com/ggreer/the_silver_searcher (Required for https://github.com/junegunn/fzf.vim)
  - exuberant-ctags  # http://ctags.sourceforge.net/  Code navigation for neovim
  - ubuntu-restricted-extras  # configure the codecs necessary to play media files
  - keepassxc  # https://keepassxc.org/
  - ncdu  # Clean up disks
  - terminator
  - gnome-tweaks  # https://gitlab.gnome.org/GNOME/gnome-tweaks
  - jq
  - libreoffice
  - smartmontools  # https://www.smartmontools.org/
  - fzf  # fuzzy finder for local scripts
  - zsh  # shell
  - vagrant
  - python3.10-venv  # package for lazyvim and ansible lint mason package
  - gparted
  - lazygit   #  nvim dep
  - fd-find   #  fdfind command. It is a nvim dep
  - ripgrep   #  nvim dep
  - gnupg     # gpg encryption
  - brave-browser
  - wezterm   # https://wezfurlong.org/wezterm/
  - luarocks  # nvim setup and plugins
  - lm-sensors  # tmux gpu/cpu temperature
  - yamllint
  - eza
  - bat

npm_glob_pkgs:
  - tree-sitter-cli  # nvim dep
  - neovim  # nvim  dep
  - yarn
  - protondb-cli

snap_pkgs:
  - discord
  - fast  # https://snapcraft.io/fast
  - postman
  - slack
  - spotify
  - teams
  - telegram-desktop
  - cacher  # https://www.cacher.io/
  - dbeaver-ce  # https://dbeaver.io/

pip_pkgs:
  - ansible-lint
  - yamllint
  - s3cmd
  - docker
  - boto
  - boto3
  - botocore
  - molecule
  - molecule-docker
  - setuptools
  - awslogs

git_repos:
  - name: fzf-git.sh  # fzf keybindings for git
    url: https://github.com/junegunn/fzf-git.sh

nvm_url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh

awscli_url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip

zsh_url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh

neovim_url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz

deb_pkgs:
  - name: franz
    url: https://github.com/meetfranz/franz/releases/download/v{{ franz_version }}/franz_{{ franz_version }}_amd64.deb

  - name: vscode
    url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

  - name: zoom
    url: https://zoom.us/client/latest/zoom_amd64.deb

  - name: chrome
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  - name: steam
    url: https://repo.steampowered.com/steam/archive/precise/steam_latest.deb

  - name: virtualbox
    url: https://download.virtualbox.org/virtualbox/7.0.10/virtualbox-7.0_7.0.10-158379~Ubuntu~jammy_amd64.deb

  - name: freetube
    url: https://github.com/FreeTubeApp/FreeTube/releases/download/v0.23.3-beta/freetube_0.23.3_amd64.deb

bash_alias_path: "{{ ansible_env.HOME }}/.bash_aliases"

bash_aliases:
  - {alias: "sudo", command: "sudo"}
  - {alias: "v", command: "nvim"}
  - {alias: "aptlist", command: "apt list --upgradable"}
  - {alias: "i", command: "ip -c -brie a"}
  - {alias: "sz", command: "du /* -xhs --exclude=/proc  | sort -hr"}
  - {alias: "geffort", command: "git log --pretty=format: --since=\\\"1 year ago\\\" --name-only | sort | uniq -c | sort -rg | head -10"}
  - {alias: "ls", command: "eza --icons=always"}
  - {alias: "cat", command: "batcat"}
