---
# https://github.com/nvm-sh/nvm
nvm_version: 0.39.0
# Franz https://meetfranz.com/
franz_version: 5.7.0
# Vagrant https://www.vagrantup.com/
vagrant_version: 2.2.19

apt_repos:
  - ppa:solaar-unifying/stable
  - ppa:cappelikan/ppa

apt_pkgs:
  - apt-transport-https
  - bash
  - bash-completion
  - build-essential
  - curl
  - docker
  - pgadmin4
  - git
  - gimp
  - vim
  - flameshot                        # https://github.com/flameshot-org/flameshot
  - shellcheck                       # https://github.com/koalaman/shellcheck
  - htop
  - solaar                           # https://pwr-solaar.github.io/Solaar/
  - firefox
  - terraform
  - mainline                         # https://github.com/bkw777/mainline
  - unzip
  - w3m
  - tmux
  - nmap
  - iotop
  - neovim
  - thunderbird
  - zfz                              # https://github.com/junegunn/fzf#using-linux-package-managers
  - silversearcher-ag                # https://github.com/ggreer/the_silver_searcher (Required for https://github.com/junegunn/fzf.vim)
  - exuberant-ctags                  # http://ctags.sourceforge.net/  Code navigation for neovim
  - ubuntu-restricted-extras         # configure the codecs necessary to play media files
  - keepassxc                        # https://keepassxc.org/
  - ncdu                             # Clean up disks

snap_pkgs:
  - discord
  - fast                             # https://snapcraft.io/fast
  - postman
  - slack
  - spotify
  - teams
  - telegram-desktop
  - cacher                           # https://www.cacher.io/
  - remmina                          # https://remmina.org/
  - dbeaver-ce                       # https://dbeaver.io/

pip_pkgs:
  - ansible-lint
  - yamllint
  - s3cmd
  - docker
  - boto
  - boto3
  - botocore
  - terminator
  - molecule
  - molecule-docker
  - setuptools
  - awslogs

nvm_url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh

awscli_url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip

deb_pkgs:

  - name: franz
    url: https://github.com/meetfranz/franz/releases/download/v{{ franz_version }}/franz_{{ franz_version }}_amd64.deb

  - name: vscode
    url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

  - name: zoom
    url: https://zoom.us/client/latest/zoom_amd64.deb

  - name: chrome
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  - name: steam
    url: https://repo.steampowered.com/steam/archive/precise/steam_latest.deb

  - name: vagrant
    url: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb

  - name: virtualbox
    url: https://download.virtualbox.org/virtualbox/6.1.30/virtualbox-6.1_6.1.30-148432~Ubuntu~eoan_amd64.deb

bash_alias_path: "{{ ansible_env.HOME }}/.bash_aliases"

bash_aliases:
  - {alias: 'sudo', command: 'sudo '}
  - {alias: 'v', command: 'nvim'}
  - {alias: 'aptlist', command: 'apt list --upgradable'}
  - {alias: 'i', command: 'ip -c -brie a'}
  - {alias: 'sz', command: 'du /* -xhs --exclude=/proc  | sort -hr' }
