---
- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - config.default.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:

    - import_tasks: tasks/apt_pkgs.yml
      tags:
        - sw
        - apt

    - import_tasks: tasks/deb_local_pkgs.yml
      tags:
        - sw
        - deb

    - import_tasks: tasks/snap_pkgs.yml
      tags:
        - sw
        - snap

    - import_tasks: tasks/pip_pkgs.yml
      tags:
        - sw
        - pip

    - import_tasks: tasks/nvm.yml
      tags:
        - sw

    - import_tasks: tasks/awscli.yml
      tags:
        - sw

    - import_tasks: tasks/local_settings.yml
      tags:
        - local

    - import_tasks: tasks/alias.yml
      tags:
        - alias
