---
- name: Ubuntu dev env installation
  hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - config.default.yml

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  tasks:
    - name: Import admin
      ansible.builtin.import_tasks: tasks/admin.yml
      tags:
        - admin

    - name: Import apt packages
      ansible.builtin.import_tasks: tasks/apt_pkgs.yml
      tags:
        - sw
        - apt

    - name: Import local and deb packages
      ansible.builtin.import_tasks: tasks/deb_local_pkgs.yml
      tags:
        - sw
        - deb

    - name: Import snap packages
      ansible.builtin.import_tasks: tasks/snap_pkgs.yml
      tags:
        - sw
        - snap

    - name: Import pip packages
      ansible.builtin.import_tasks: tasks/pip_pkgs.yml
      tags:
        - sw
        - pip

    # - ansible.builtin.import_tasks: tasks/nvm.yml
    #   tags:
    #     - sw

    - name: Import awscli
      ansible.builtin.import_tasks: tasks/awscli.yml
      tags:
        - sw
        - awscli

    - name: Import local settings
      ansible.builtin.import_tasks: tasks/local_settings.yml
      tags:
        - local

    - name: Import alias
      ansible.builtin.import_tasks: tasks/alias.yml
      tags:
        - alias
