---
- hosts: all
  become: yes

  vars_files:
    - vars/default.yml

  tasks:
    - name: apt dist-upgrade
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist
      tags:
        - apt
        - upgrade

    - import_tasks: tasks/apt_pkgs.yml
      tags:
        - apt
