---
- hosts: all
  become: yes

  vars_files:
    - vars/default.yml

  tasks:

    - import_tasks: tasks/apt_pkgs.yml
      tags:
        - apt

    - import_tasks: tasks/snap_pkgs.yml
      tags:
        - snap

    - import_tasks: tasks/pip_pkgs.yml
      tags:
        - pip

    - import_tasks: tasks/nvm.yml
      tags:
        - nvm
