---
- name: Get user
  ansible.builtin.command: whoami
  register: whoami
  changed_when: no

- name: Define admin user
  ansible.builtin.set_fact:
    admin_user: "{{ whoami.stdout }}"

- name: Add user to sudoers
  ansible.builtin.template:
    src: templates/admin.sudoers.j2
    dest: /etc/sudoers.d/{{ admin_user }}
    validate: "visudo -cf %s"
    mode: 0440
  become: yes
  become_user: root

- name: Copy ssh config file
  ansible.builtin.copy:
    src: files/ssh/config
    dest: ~/.ssh/config
    mode: 0644
