---
- name: Add aliases
  ansible.builtin.lineinfile:
    dest: "{{ bash_alias_path }}"
    create: yes
    mode: 0644
    line: 'alias {{ item.alias }}="{{ item.command }}"'
    regexp: "^alias {{ item.alias }}="
  with_items: "{{ bash_aliases }}"
