---
- name: Check if aws cli is already installed
  ansible.builtin.command: aws --version
  ignore_errors: yes
  register: awscli_version
  changed_when: awscli_version.rc != 0

- name: Extract awscli in /tmp folder
  ansible.builtin.unarchive:
    src: "{{ awscli_url }}"
    dest: /tmp
    remote_src: yes

- name: Install aws cli ( first time )
  ansible.builtin.command: /tmp/aws/install -i /usr/local/aws-cli -b /usr/local/bin
  become: yes
  when: awscli_version.rc > 0
  changed_when: awscli_version.rc > 0
  become_user: root

- name: Update aws cli
  ansible.builtin.command: >-
    /tmp/aws/install -i /usr/local/aws-cli -b /usr/local/bin --update
  register: awscli_update
  become: yes
  when: awscli_version.rc == 0
  changed_when: >-
    'Skipping install' not in awscli_update.stdout
  become_user: root
