---
- name: Add checkout alias
  community.general.git_config:
    name: alias.co
    scope: global
    value: checkout

- name: Add status alias
  community.general.git_config:
    name: alias.st
    scope: global
    value: status -sb

- name: Add push alias
  community.general.git_config:
    name: alias.p
    scope: global
    value: push

- name: Add push alias
  community.general.git_config:
    name: alias.lg
    scope: global
    value: log --oneline

- name: Add last alias
  community.general.git_config:
    name: alias.last
    scope: global
    value: log -1 HEAD --stat