---
- name: Remove existing Neovim directory if it exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/nvim-linux64-backup"
    state: absent

- name: Copy Neovim folder to new location
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/nvim-linux64"
    dest: "{{ ansible_env.HOME }}/nvim-linux64-backup"
    remote_src: yes
    mode: preserve

- name: Create neovim directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/nvim-linux64"
    state: directory
    mode: '0755'

- name: Extract neovim in /home folder
  ansible.builtin.unarchive:
    src: "{{ neovim_url }}"
    dest: "{{ ansible_env.HOME }}/nvim-linux64"
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: "{{ ansible_env.HOME }}/nvim-linux64/bin/nvim"

- name: Ensure Neovim symlink is correct
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/nvim-linux64/bin/nvim"
    dest: "/usr/local/bin/nvim"
    state: link
    force: yes
