---
- name: Extract neovim in /home folder
  ansible.builtin.unarchive:
    src: "{{ neovim_url }}"
    dest: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/nvim-linux64"
    remote_src: yes
