---
- name: Download pnpm-installer
  ansible.builtin.get_url:
    url: "{{ pnpm_url }}"
    dest: /tmp/pnpm-installer.sh
    mode: 0744
  changed_when: no

- name: Execute the pnpm-installer.sh
  ansible.builtin.command: /tmp/pnpm-installer.sh
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/pnpm/pnpm"
