---
apt_pkgs:
  - bash
  - bash-completion
  - build-essential
  - curl
  - docker
  - pgadmin4
  - git
  - gimp
  - vim
  - flameshot
  - shellcheck

nvm_version: 0.39.0
nvm_url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh
